version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./logs:/var/log/nginx
      - ./application:/var/www/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=hw2.local
      - NGINX_PORT=80
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    environment:
      PHP_ENABLE_XDEBUG: 1
    volumes:
      - ./application:/var/www/html
      - ./docker/php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9000:9000"
  database:
    container_name: postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - "9515:5432"
    volumes:
      - postgresqldata:/var/lib/postgresql/data:delegated

volumes:
  postgresqldata: { }
