version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./logs:/var/log/nginx
      - ./application:/var/www/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=hw2.local
      - NGINX_PORT=80
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    environment:
      PHP_ENABLE_XDEBUG: 1
    volumes:
      - ./application:/var/www/html
      - ./docker/php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9000:9000"
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [5432]
  redis:
    image: redis:5-alpine
    ports: [6379]
  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [5672, 15672]
  geoserver:
    image: geosolutionsit/geoserver
    env_file: .env
    ports:
      - 8980:8080
    volumes:
      - ./logs:${GEOSERVER_LOG_DIR}
      - ./datadir:${GEOSERVER_DATA_DIR}
      - ./gwc_config:${GEOWEBCACHE_CONFIG_DIR}
      - ./gwc:${GEOWEBCACHE_CACHE_DIR}
      - ./netcfd:${NETCDF_DATA_DIR}
      - ./grib_cache:${GRIB_CACHE_DIR}